from datetime import date
from decimal import Decimal
from typing import Protocol
from pontos.dominio.modelos import Campanha, Lancamento, Lote, Produto


class RepositorioPontos(Protocol):
    def campanhas(self) -> list[Campanha]: ...
    def salvar_campanha(self, campanha: Campanha) -> None: ...
    def compra_existe(self, compra_id: str) -> bool: ...
    def salvar_compra(self, lote: Lote, valor: Decimal, multiplicador: int) -> None: ...
    def lotes_do_cliente(self, cliente_id: int) -> list[Lote]: ...
    def lancamentos_do_cliente(self, cliente_id: int) -> list[Lancamento]: ...
    def salvar_lancamentos(self, lancamentos: list[Lancamento]) -> None: ...
    def produto_em(self, produto_id: str, em: date) -> Produto | None: ...
    def salvar_produto(self, produto: Produto) -> None: ...
    def resgate_existe(self, resgate_id: str) -> bool: ...
    def salvar_resgate(self, resgate_id: str, cliente_id: int, produto_id: str, custo_pontos: int, em: date, lancamentos: list[Lancamento]) -> None: ...
    def estorno_existe(self, estorno_id: str) -> bool: ...
